# Generated by Django 5.1.2 on 2025-04-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(default=6, max_length=6),
            preserve_default=False,
        ),
    ]
